CREATE TABLE IF NOT EXISTS "turismo" (
	"id" serial PRIMARY KEY NOT NULL,
	"client_name" text NOT NULL,
	"tipo_de_visto" text NOT NULL,
	"data_emissao" text,
	"data_validade" text,
	"status" text DEFAULT 'Em Andamento' NOT NULL,
	"observacoes" text,
	"documentos_anexos" text,
	"numero_processo" text,
	"country" text,
	"travel_start_date" text,
	"travel_end_date" text,
	"current_step" integer DEFAULT 0,
	"completed_steps" text,
	"cpf" text,
	"cpf_doc" text,
	"rnm" text,
	"rnm_doc" text,
	"passaporte" text,
	"passaporte_doc" text,
	"comprovante_endereco" text,
	"comprovante_endereco_doc" text,
	"declaracao_residencia_doc" text,
	"foto_3x4_doc" text,
	"documento_chines" text,
	"documento_chines_doc" text,
	"antecedentes_criminais" text,
	"antecedentes_criminais_doc" text,
	"certidao_nascimento_filhos" text,
	"certidao_nascimento_filhos_doc" text,
	"cartao_cnpj" text,
	"cartao_cnpj_doc" text,
	"contrato_empresa" text,
	"contrato_empresa_doc" text,
	"escritura_imoveis" text,
	"escritura_imoveis_doc" text,
	"extratos_bancarios" text,
	"extratos_bancarios_doc" text,
	"imposto_renda" text,
	"imposto_renda_doc" text,
	"reservas_passagens" text,
	"reservas_passagens_doc" text,
	"reservas_hotel" text,
	"reservas_hotel_doc" text,
	"seguro_viagem" text,
	"seguro_viagem_doc" text,
	"roteiro_viagem" text,
	"roteiro_viagem_doc" text,
	"taxa" text,
	"taxa_doc" text,
	"formulario_consulado" text,
	"formulario_consulado_doc" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);

-- Migrate data
INSERT INTO "turismo" (
    client_name, 
    tipo_de_visto, 
    status, 
    observacoes,
    country,
    travel_start_date,
    travel_end_date,
    current_step,
    completed_steps,
    cpf, cpf_doc,
    rnm, rnm_doc,
    passaporte, passaporte_doc,
    comprovante_endereco, comprovante_endereco_doc,
    declaracao_residencia_doc,
    foto_3x4_doc,
    documento_chines, documento_chines_doc,
    antecedentes_criminais, antecedentes_criminais_doc,
    certidao_nascimento_filhos, certidao_nascimento_filhos_doc,
    cartao_cnpj, cartao_cnpj_doc,
    contrato_empresa, contrato_empresa_doc,
    escritura_imoveis, escritura_imoveis_doc,
    extratos_bancarios, extratos_bancarios_doc,
    imposto_renda, imposto_renda_doc,
    reservas_passagens, reservas_passagens_doc,
    reservas_hotel, reservas_hotel_doc,
    seguro_viagem, seguro_viagem_doc,
    roteiro_viagem, roteiro_viagem_doc,
    taxa, taxa_doc,
    formulario_consulado, formulario_consulado_doc,
    created_at, updated_at,
    -- Map existing dates to new fields
    data_emissao,
    data_validade
)
SELECT 
    client_name, 
    type as tipo_de_visto, 
    status, 
    notes as observacoes,
    country,
    travel_start_date,
    travel_end_date,
    current_step,
    completed_steps,
    cpf, cpf_doc,
    rnm, rnm_doc,
    passaporte, passaporte_doc,
    comprovante_endereco, comprovante_endereco_doc,
    declaracao_residencia_doc,
    foto_3x4_doc,
    documento_chines, documento_chines_doc,
    antecedentes_criminais, antecedentes_criminais_doc,
    certidao_nascimento_filhos, certidao_nascimento_filhos_doc,
    cartao_cnpj, cartao_cnpj_doc,
    contrato_empresa, contrato_empresa_doc,
    escritura_imoveis, escritura_imoveis_doc,
    extratos_bancarios, extratos_bancarios_doc,
    imposto_renda, imposto_renda_doc,
    reservas_passagens, reservas_passagens_doc,
    reservas_hotel, reservas_hotel_doc,
    seguro_viagem, seguro_viagem_doc,
    roteiro_viagem, roteiro_viagem_doc,
    taxa, taxa_doc,
    formulario_consulado, formulario_consulado_doc,
    created_at, updated_at,
    travel_start_date as data_emissao,
    travel_end_date as data_validade
FROM "vistos"
WHERE type = 'Turismo' OR type = 'Visto de Turismo';

-- Delete migrated data
DELETE FROM "vistos" WHERE type = 'Turismo' OR type = 'Visto de Turismo';
