import { pgTable, serial, text, integer, boolean, timestamp } from 'drizzle-orm/pg-core';

// Users table
export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  email: text('email').notNull().unique(),
  password: text('password').notNull(),
  name: text('name').notNull(),
  role: text('role').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// Ações Civeis table
export const acoesCiveis = pgTable('acoes_civeis', {
  id: serial('id').primaryKey(),
  clientName: text('client_name').notNull(),
  type: text('type').notNull(),
  currentStep: integer('current_step').default(0),
  status: text('status').notNull().default('Em Andamento'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  rnmMae: text('rnm_mae'),
  rnmPai: text('rnm_pai'),
  rnmSupostoPai: text('rnm_suposto_pai'),
  nomeMae: text('nome_mae'),
  nomePaiRegistral: text('nome_pai_registral'),
  nomeSupostoPai: text('nome_suposto_pai'),
  cpfMae: text('cpf_mae'),
  cpfPai: text('cpf_pai'),
  certidaoNascimento: text('certidao_nascimento'),
  comprovanteEndereco: text('comprovante_endereco'),
  passaporte: text('passaporte'),
  guiaPaga: text('guia_paga'),
  notes: text('notes'),
  // Step 2 fields
  dataExameDna: text('data_exame_dna'),
  // Step 3 fields
  procuracaoAnexada: text('procuracao_anexada'),
  // Step 4 fields
  peticaoAnexada: text('peticao_anexada'),
  // Step 5 fields
  processoAnexado: text('processo_anexado'),
  numeroProtocolo: text('numero_protocolo'),
  // Step 6 fields
  documentosFinaisAnexados: text('documentos_finais_anexados'),
  // Document URL fields for file uploads
  rnmMaeFile: text('rnm_mae_file'),
  rnmPaiFile: text('rnm_pai_file'),
  rnmSupostoPaiFile: text('rnm_suposto_pai_file'),
  cpfMaeFile: text('cpf_mae_file'),
  cpfPaiFile: text('cpf_pai_file'),
  certidaoNascimentoFile: text('certidao_nascimento_file'),
  comprovanteEnderecoFile: text('comprovante_endereco_file'),
  passaporteFile: text('passaporte_file'),
  guiaPagaFile: text('guia_paga_file'),
  resultadoExameDnaFile: text('resultado_exame_dna_file'),
  procuracaoAnexadaFile: text('procuracao_anexada_file'),
  peticaoAnexadaFile: text('peticao_anexada_file'),
  processoAnexadoFile: text('processo_anexado_file'),
  documentosFinaisAnexadosFile: text('documentos_finais_anexados_file'),
  documentosProcessoFinalizadoFile: text('documentos_processo_finalizado_file'),
});

// Compra Venda Imoveis table
export const compraVendaImoveis = pgTable('compra_venda_imoveis', {
  id: serial('id').primaryKey(),
  numeroMatricula: text('numero_matricula'),
  cadastroContribuinte: text('cadastro_contribuinte'),
  enderecoImovel: text('endereco_imovel'),
  rgVendedores: text('rg_vendedores'),
  cpfVendedores: text('cpf_vendedores'),
  dataNascimentoVendedores: text('data_nascimento_vendedores'),
  rnmComprador: text('rnm_comprador'),
  cpfComprador: text('cpf_comprador'),
  enderecoComprador: text('endereco_comprador'),
  currentStep: integer('current_step').default(0),
  status: text('status').notNull().default('Em Andamento'),
  prazoSinal: text('prazo_sinal'),
  prazoEscritura: text('prazo_escritura'),
  contractNotes: text('contract_notes'),
  stepNotes: text('step_notes'),
  completedSteps: text('completed_steps', { mode: 'json' }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Perda Nacionalidade table
export const perdaNacionalidade = pgTable('perda_nacionalidade', {
  id: serial('id').primaryKey(),
  clientName: text('client_name').notNull(),
  rnmMae: text('rnm_mae'),
  rnmPai: text('rnm_pai'),
  nomeMae: text('nome_mae'),
  nomePaiRegistral: text('nome_pai_registral'),
  cpfMae: text('cpf_mae'),
  cpfPai: text('cpf_pai'),
  certidaoNascimento: text('certidao_nascimento'),
  comprovanteEndereco: text('comprovante_endereco'),
  passaportes: text('passaportes'),
  documentoChines: text('documento_chines'),
  traducaoJuramentada: text('traducao_juramentada'),
  currentStep: integer('current_step').default(0),
  status: text('status').notNull().default('Em Andamento'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Vistos table
export const vistos = pgTable('vistos', {
  id: serial('id').primaryKey(),
  clientName: text('client_name').notNull(),
  type: text('type').notNull(),
  country: text('country'),
  travelStartDate: text('travel_start_date'),
  travelEndDate: text('travel_end_date'),
  currentStep: integer('current_step').default(0),
  completedSteps: text('completed_steps', { mode: 'json' }),
  cpf: text('cpf'),
  cpfDoc: text('cpf_doc'),
  rnm: text('rnm'),
  rnmDoc: text('rnm_doc'),
  passaporte: text('passaporte'),
  passaporteDoc: text('passaporte_doc'),
  comprovanteEndereco: text('comprovante_endereco'),
  comprovanteEnderecoDoc: text('comprovante_endereco_doc'),
  declaracaoResidenciaDoc: text('declaracao_residencia_doc'),
  foto3x4Doc: text('foto_3x4_doc'),
  documentoChines: text('documento_chines'),
  documentoChinesDoc: text('documento_chines_doc'),
  antecedentesCriminais: text('antecedentes_criminais'),
  antecedentesCriminaisDoc: text('antecedentes_criminais_doc'),
  certidaoNascimentoFilhos: text('certidao_nascimento_filhos'),
  certidaoNascimentoFilhosDoc: text('certidao_nascimento_filhos_doc'),
  cartaoCnpj: text('cartao_cnpj'),
  cartaoCnpjDoc: text('cartao_cnpj_doc'),
  contratoEmpresa: text('contrato_empresa'),
  contratoEmpresaDoc: text('contrato_empresa_doc'),
  escrituraImoveis: text('escritura_imoveis'),
  escrituraImoveisDoc: text('escritura_imoveis_doc'),
  extratosBancarios: text('extratos_bancarios'),
  extratosBancariosDoc: text('extratos_bancarios_doc'),
  impostoRenda: text('imposto_renda'),
  impostoRendaDoc: text('imposto_renda_doc'),
  reservasPassagens: text('reservas_passagens'),
  reservasPassagensDoc: text('reservas_passagens_doc'),
  reservasHotel: text('reservas_hotel'),
  reservasHotelDoc: text('reservas_hotel_doc'),
  seguroViagem: text('seguro_viagem'),
  seguroViagemDoc: text('seguro_viagem_doc'),
  roteiroViagem: text('roteiro_viagem'),
  roteiroViagemDoc: text('roteiro_viagem_doc'),
  taxa: text('taxa'),
  taxaDoc: text('taxa_doc'),
  formularioConsulado: text('formulario_consulado'),
  formularioConsuladoDoc: text('formulario_consulado_doc'),
  comprovanteResidenciaPrevia: text('comprovante_residencia_previa'),
  comprovanteResidenciaPreviaDoc: text('comprovante_residencia_previa_doc'),
  formularioRn02: text('formulario_rn02'),
  formularioRn02Doc: text('formulario_rn02_doc'),
  comprovanteAtividade: text('comprovante_atividade'),
  comprovanteAtividadeDoc: text('comprovante_atividade_doc'),
  // Novos campos para Visto de Trabalho - Brasil
  certidaoNascimento: text('certidao_nascimento'),
  certidaoNascimentoDoc: text('certidao_nascimento_doc'),
  declaracaoCompreensao: text('declaracao_compreensao'),
  declaracaoCompreensaoDoc: text('declaracao_compreensao_doc'),
  declaracoesEmpresa: text('declaracoes_empresa'),
  declaracoesEmpresaDoc: text('declaracoes_empresa_doc'),
  procuracaoEmpresa: text('procuracao_empresa'),
  procuracaoEmpresaDoc: text('procuracao_empresa_doc'),
  formularioRn01: text('formulario_rn01'),
  formularioRn01Doc: text('formulario_rn01_doc'),
  guiaPaga: text('guia_paga'),
  guiaPagaDoc: text('guia_paga_doc'),
  dou: text('dou'),
  douDoc: text('dou_doc'),
  comprovanteInvestimento: text('comprovante_investimento'),
  comprovanteInvestimentoDoc: text('comprovante_investimento_doc'),
  planoInvestimentos: text('plano_investimentos'),
  planoInvestimentosDoc: text('plano_investimentos_doc'),
  formularioRequerimento: text('formulario_requerimento'),
  formularioRequerimentoDoc: text('formulario_requerimento_doc'),
  protocolado: text('protocolado'),
  protocoladoDoc: text('protocolado_doc'),
  contratoTrabalho: text('contrato_trabalho'),
  contratoTrabalhoDoc: text('contrato_trabalho_doc'),
  folhaPagamento: text('folha_pagamento'),
  folhaPagamentoDoc: text('folha_pagamento_doc'),
  comprovanteVinculoAnterior: text('comprovante_vinculo_anterior'),
  comprovanteVinculoAnteriorDoc: text('comprovante_vinculo_anterior_doc'),
  declaracaoAntecedentesCriminais: text('declaracao_antecedentes_criminais'),
  declaracaoAntecedentesCriminaisDoc: text('declaracao_antecedentes_criminais_doc'),
  diploma: text('diploma'),
  diplomaDoc: text('diploma_doc'),
  contratoTrabalhoIndeterminado: text('contrato_trabalho_indeterminado'),
  contratoTrabalhoIndeterminadoDoc: text('contrato_trabalho_indeterminado_doc'),
  procurador: text('procurador'),
  numeroProcesso: text('numero_processo'),
  // Renovação 1 ano
  ctps: text('ctps'),
  ctpsDoc: text('ctps_doc'),
  contratoTrabalhoAnterior: text('contrato_trabalho_anterior'),
  contratoTrabalhoAnteriorDoc: text('contrato_trabalho_anterior_doc'),
  contratoTrabalhoAtual: text('contrato_trabalho_atual'),
  contratoTrabalhoAtualDoc: text('contrato_trabalho_atual_doc'),
  formularioProrrogacao: text('formulario_prorrogacao'),
  formularioProrrogacaoDoc: text('formulario_prorrogacao_doc'),
  justificativaMudancaEmpregador: text('justificativa_mudanca_empregador'),
  justificativaMudancaEmpregadorDoc: text('justificativa_mudanca_empregador_doc'),
  statusFinal: text('status_final'),
  statusFinalOutro: text('status_final_outro'),
  notes: text('notes'),
  status: text('status').notNull().default('Em Andamento'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Turismo table (New separate module)
export const turismo = pgTable('turismo', {
  id: serial('id').primaryKey(),
  clientName: text('client_name').notNull(),
  tipoDeVisto: text('tipo_de_visto').notNull(), // Replaces 'type'
  dataEmissao: text('data_emissao'), // New field
  dataValidade: text('data_validade'), // New field
  status: text('status').notNull().default('Em Andamento'),
  observacoes: text('observacoes'), // Replaces 'notes'
  documentosAnexos: text('documentos_anexos', { mode: 'json' }), // New optional field
  numeroProcesso: text('numero_processo'),
  
  // Legacy/Compatible fields from Vistos for migration and file uploads
  country: text('country'),
  travelStartDate: text('travel_start_date'),
  travelEndDate: text('travel_end_date'),
  currentStep: integer('current_step').default(0),
  completedSteps: text('completed_steps', { mode: 'json' }),
  cpf: text('cpf'),
  cpfDoc: text('cpf_doc'),
  rnm: text('rnm'),
  rnmDoc: text('rnm_doc'),
  passaporte: text('passaporte'),
  passaporteDoc: text('passaporte_doc'),
  comprovanteEndereco: text('comprovante_endereco'),
  comprovanteEnderecoDoc: text('comprovante_endereco_doc'),
  declaracaoResidenciaDoc: text('declaracao_residencia_doc'),
  foto3x4Doc: text('foto_3x4_doc'),
  documentoChines: text('documento_chines'),
  documentoChinesDoc: text('documento_chines_doc'),
  antecedentesCriminais: text('antecedentes_criminais'),
  antecedentesCriminaisDoc: text('antecedentes_criminais_doc'),
  certidaoNascimentoFilhos: text('certidao_nascimento_filhos'),
  certidaoNascimentoFilhosDoc: text('certidao_nascimento_filhos_doc'),
  cartaoCnpj: text('cartao_cnpj'),
  cartaoCnpjDoc: text('cartao_cnpj_doc'),
  contratoEmpresa: text('contrato_empresa'),
  contratoEmpresaDoc: text('contrato_empresa_doc'),
  escrituraImoveis: text('escritura_imoveis'),
  escrituraImoveisDoc: text('escritura_imoveis_doc'),
  extratosBancarios: text('extratos_bancarios'),
  extratosBancariosDoc: text('extratos_bancarios_doc'),
  impostoRenda: text('imposto_renda'),
  impostoRendaDoc: text('imposto_renda_doc'),
  reservasPassagens: text('reservas_passagens'),
  reservasPassagensDoc: text('reservas_passagens_doc'),
  reservasHotel: text('reservas_hotel'),
  reservasHotelDoc: text('reservas_hotel_doc'),
  seguroViagem: text('seguro_viagem'),
  seguroViagemDoc: text('seguro_viagem_doc'),
  roteiroViagem: text('roteiro_viagem'),
  roteiroViagemDoc: text('roteiro_viagem_doc'),
  taxa: text('taxa'),
  taxaDoc: text('taxa_doc'),
  formularioConsulado: text('formulario_consulado'),
  formularioConsuladoDoc: text('formulario_consulado_doc'),
  
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Documents table
export const documents = pgTable('documents', {
  id: serial('id').primaryKey(),
  moduleType: text('module_type').notNull(),
  recordId: integer('record_id').notNull(),
  fileName: text('file_name').notNull(),
  filePath: text('file_path').notNull(),
  fileType: text('file_type').notNull(),
  uploadedAt: timestamp('uploaded_at').defaultNow().notNull(),
});

// Alerts table
export const alerts = pgTable('alerts', {
  id: serial('id').primaryKey(),
  moduleType: text('module_type').notNull(),
  recordId: integer('record_id').notNull(),
  alertFor: text('alert_for').notNull(),
  message: text('message').notNull(),
  data: text('data'),
  status: text('status').default('pending').notNull(),
  retryCount: integer('retry_count').default(0).notNull(),
  isRead: boolean('is_read').default(false),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Ações Trabalhistas table
export const acoesTrabalhistas = pgTable('acoes_trabalhistas', {
  id: serial('id').primaryKey(),
  clientName: text('client_name').notNull(),
  status: text('status').notNull().default('Em Andamento'),
  notes: text('notes'),
  currentStep: integer('current_step').default(0),
  // New fields
  reuName: text('reu_name'),
  autorName: text('autor_name'),
  numeroProcesso: text('numero_processo'),
  responsavelName: text('responsavel_name'),
  responsavelDate: text('responsavel_date'),
  resumo: text('resumo'),
  acompanhamento: text('acompanhamento'),
  contratado: text('contratado'),
  fotoNotificacaoDoc: text('foto_notificacao_doc'),
  
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// Ações Criminais table
export const acoesCriminais = pgTable('acoes_criminais', {
  id: serial('id').primaryKey(),
  clientName: text('client_name').notNull(),
  status: text('status').notNull().default('Em Andamento'),
  notes: text('notes'),
  // Campos extras para novo formulário
  reuName: text('reu_name'),
  autorName: text('autor_name'),
  numeroProcesso: text('numero_processo'),
  responsavelName: text('responsavel_name'),
  responsavelDate: text('responsavel_date'),
  resumo: text('resumo'),
  acompanhamento: text('acompanhamento'),
  contratado: text('contratado'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});
